# Generated by Django 6.1.1 on 2026-09-03 16:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Full description. Can be AI-generated from a pasted WhatsApp message.')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('utilities_included', models.BooleanField(default=False, help_text='True if electricity, water, internet are all bundled into the rent.')),
                ('building_name', models.CharField(blank=True, help_text='Public-facing building name shown before address is revealed.', max_length=200)),
                ('street_address', models.CharField(help_text='Full address — only revealed to seekers after an inquiry is accepted.', max_length=300)),
                ('unit_number', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(default='Champaign', max_length=100)),
                ('state', models.CharField(default='IL', max_length=2)),
                ('zip_code', models.CharField(default='61820', max_length=10)),
                ('walk_min_to_quad', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('walk_min_to_green_st', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('walk_min_to_arc', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mtd_stop_nearby', models.BooleanField(default=False)),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_private_bedroom', models.BooleanField(default=True, help_text='True if the subleasee gets a private, lockable bedroom.')),
                ('is_private_bathroom', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('has_in_unit_laundry', models.BooleanField(default=False)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('ac_included', models.BooleanField(default=True)),
                ('available_from', models.DateField()),
                ('available_until', models.DateField()),
                ('gender_preference', models.CharField(choices=[('any', 'Any'), ('male', 'Males only'), ('female', 'Females only')], default='any', max_length=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('filled', 'Filled')], default='available', max_length=10)),
                ('is_property_verified', models.BooleanField(default=False, help_text='True once the lister has uploaded proof of lease.')),
                ('lease_document', models.FileField(blank=True, help_text='Private document — only visible to admins for verification.', null=True, upload_to='lease_docs/')),
                ('external_listing_url', models.URLField(blank=True, help_text='Optional link to official property manager listing (e.g. Smile Living).')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('inquiry_count', models.PositiveIntegerField(default=0)),
                ('ai_parsed', models.BooleanField(default=False, help_text='True if this listing was created via the WhatsApp message parser.')),
                ('raw_whatsapp_text', models.TextField(blank=True, help_text='Original pasted WhatsApp message stored for audit/re-parsing.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text="Seeker's initial message to the lister.")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries_sent', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='listings.listing')),
            ],
            options={
                'verbose_name': 'Inquiry',
                'verbose_name_plural': 'Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='listings.listing')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Listing',
                'verbose_name_plural': 'Saved Listings',
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_start', models.DateTimeField()),
                ('slot_end', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False, help_text='True once the 24-hour reminder notification has been dispatched.')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_slots', to='listings.listing')),
                ('seeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit Slot',
                'verbose_name_plural': 'Visit Slots',
                'ordering': ['slot_start'],
            },
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('lister', 'street_address', 'unit_number', 'available_from'), name='unique_listing_per_lister_unit_date'),
        ),
        migrations.AddConstraint(
            model_name='inquiry',
            constraint=models.UniqueConstraint(fields=('listing', 'seeker'), name='unique_inquiry_per_seeker_listing'),
        ),
        migrations.AddConstraint(
            model_name='savedlisting',
            constraint=models.UniqueConstraint(fields=('seeker', 'listing'), name='unique_save_per_seeker_listing'),
        ),
        migrations.AddConstraint(
            model_name='visitslot',
            constraint=models.UniqueConstraint(fields=('listing', 'slot_start'), name='unique_slot_per_listing_time'),
        ),
    ]
