# Generated by Django 6.1 on 2026-09-07 22:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='saved_by_users',
            field=models.ManyToManyField(blank=True, related_name='favorites', through='listings.SavedListing', to=settings.AUTH_USER_MODEL),
        ),
    ]
