# Generated by Django 6.1 on 2026-09-07 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_saved_by_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='mtd_stop_nearby',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='walk_min_to_arc',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='walk_min_to_green_st',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='walk_min_to_quad',
        ),
    ]
