# Generated by Django 6.1.1 on 2026-09-03 16:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnleasedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('lister', 'Lister'), ('seeker', 'Seeker'), ('both', 'Both')], default='seeker', help_text='Whether this user is listing a place, seeking one, or both.', max_length=10)),
                ('edu_email', models.EmailField(help_text='Must be a .edu address. Used for university verification.', max_length=254, unique=True)),
                ('is_edu_verified', models.BooleanField(default=False, help_text='Set to True once the .edu email link is confirmed.')),
                ('bio', models.TextField(blank=True, help_text="Short personal description shown on the user's public profile.")),
                ('sleep_schedule', models.CharField(blank=True, choices=[('early', 'Early bird'), ('night', 'Night owl'), ('flexible', 'Flexible')], max_length=20)),
                ('cleanliness', models.CharField(blank=True, choices=[('very_clean', 'Very clean'), ('moderate', 'Moderate'), ('relaxed', 'Relaxed')], max_length=20)),
                ('noise_level', models.CharField(blank=True, choices=[('quiet', 'Quiet'), ('moderate', 'Moderate'), ('social', 'Social/loud')], max_length=20)),
                ('guests_policy', models.CharField(blank=True, choices=[('rarely', 'Rarely'), ('sometimes', 'Sometimes'), ('often', 'Often')], max_length=20)),
                ('pets_ok', models.BooleanField(default=False)),
                ('response_rate', models.FloatField(default=0.0, help_text='Percentage of inquiries responded to within 24 hours (0–100).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Unleased User',
                'verbose_name_plural': 'Unleased Users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 star rating.')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Review',
                'verbose_name_plural': 'User Reviews',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'reviewee'), name='unique_review_per_pair')],
            },
        ),
    ]
