# Generated by Django 5.2.17 on 2026-10-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unleaseduser',
            name='edu_email',
            field=models.EmailField(blank=True, help_text='Filled from the account email on save (see accounts/signals.py). .edu addresses are marked as verified.', max_length=254, null=True, unique=True),
        ),
    ]
